# Modo Full - Caddy + Cloudflare para máxima flexibilidad
services:
  # Los servicios base solo exponen internamente
  flowise:
    expose:
      - 3001/tcp

  open-webui:
    expose:
      - 8080/tcp

  n8n:
    expose:
      - 5678/tcp
    environment:
      - WEBHOOK_URL=https://n8n.${CLOUDFLARE_DOMAIN}

  qdrant:
    expose:
      - 6333/tcp
      - 6334/tcp

  redis:
    expose:
      - 6379/tcp

  searxng:
    expose:
      - 8080/tcp
    environment:
      - SEARXNG_BASE_URL=https://searxng.${CLOUDFLARE_DOMAIN}/

  # Caddy con puertos para acceso directo Y tunnel
  caddy:
    ports:
      - "80:80"
      - "443:443"
    environment:
      - N8N_HOSTNAME=n8n.${CLOUDFLARE_DOMAIN}
      - WEBUI_HOSTNAME=openwebui.${CLOUDFLARE_DOMAIN}
      - FLOWISE_HOSTNAME=flowise.${CLOUDFLARE_DOMAIN}
      - SEARXNG_HOSTNAME=searxng.${CLOUDFLARE_DOMAIN}
      - SUPABASE_HOSTNAME=supabase.${CLOUDFLARE_DOMAIN}
      - QDRANT_HOSTNAME=qdrant.${CLOUDFLARE_DOMAIN}