# Modo Caddy - Servicios expuestos a través de Caddy con SSL automático
services:
  # Los servicios base no exponen puertos - todo va a través de Caddy
  flowise:
    expose:
      - 3001/tcp

  open-webui:
    expose:
      - 8080/tcp

  n8n:
    expose:
      - 5678/tcp

  qdrant:
    expose:
      - 6333/tcp
      - 6334/tcp

  redis:
    expose:
      - 6379/tcp

  searxng:
    expose:
      - 8080/tcp
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME}/