# Configuración para Cloudflare Tunnel - Modo con Rutas
# Personaliza los valores tunnel y hostname según tu configuración

tunnel: tu-tunnel-id-aqui
credentials-file: /etc/cloudflared/credentials.json

# Configuración de ingress - rutas para acceso unificado
ingress:
  # Dominio principal con rutas
  - hostname: ai.tudominio.com
    service: http://caddy:80
    originRequest:
      httpHostHeader: ai.tudominio.com
      noTLSVerify: true

  # Catch-all rule (debe ir al final)
  - service: http_status:404

# Configuración de logging
loglevel: info

# Configuración de métricas (opcional)
metrics: 0.0.0.0:2000